pipeline {
    agent {
        docker {
            image 'python:2.7.16-slim'
	    args '--user root'
	}
    }
    stages {
        stage('build') {
	    when {
	        changeset "**/vote/**"
	    }
            steps {
               echo 'Compiling vote app' 
               dir('vote') {
                 sh 'pip install -r requirements.txt' 
               }
            }
        }
        stage('test') {
	    when {
	        changeset "**/vote/**"
	    }
            steps {
                echo 'Running Unit Tests on vote app'
                dir('vote') {
                  sh 'nosetests -v' 
                }
            }
        }
    }
    post {
        success {
            slackSend color: "good", message: "vote pipeline successfully completed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
	}
	failure {
            slackSend color: "danger", message: "vote pipeline failed - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)"
	}
        always {
            echo 'Pipeline for vote is complete'
        }

    }
    
}
