pipeline {
    agent any
    tools {
        maven 'Maven 3.8.3'
    }
    stages {
        stage('build') {
	    when {
	        changeset "**/worker/**"
	    }
            steps {
               echo 'Compiling worker app' 
               dir('worker') {
                 sh 'mvn compile' 
               }
            }
        }
        stage('test') {
	    when {
	        changeset "**/worker/**"
	    }
            steps {
                echo 'Running Unit Tests on worker app'
                dir('worker') {
                  sh 'mvn clean test' 
                }
            }
        }
        stage('package') {
	    when {
	        changeset "**/worker/**"
                branch 'master'
	    }
            steps {
                echo 'Packaging worker app'
                dir('worker') {
                  sh 'mvn package -DskipTests' 
	          archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                }
            }
        }
    }
    post {
        always {
            echo 'Pipeline for worker is complete'
        }
    }
    
}
